# This file contains only the changes from the defaults
# https://jekyllrb.com/docs/configuration/#default-configuration

# Make our URLs look nice. We're not a blog with dated posts, we just want the title.
permalink:     /:title.html

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

url: https://docs.projectcalico.org

repository: projectcalico/calico

prodname: Calico
nodecontainer: calico/node
noderunning: calico-node

# Image names in case the host changes
imageNames:
  node: quay.io/calico/node
  calicoctl: quay.io/calico/ctl
  typha: quay.io/calico/typha
  cni: quay.io/calico/cni
  kubeControllers: quay.io/calico/kube-controllers
  calico-upgrade: quay.io/calico/upgrade
  flannel: quay.io/coreos/flannel
  dikastes: quay.io/calico/dikastes
  pilot-webhook: quay.io/calico/pilot-webhook
  flexvol: quay.io/calico/pod2daemon-flexvol

exclude:
  - release-scripts
  - LICENSE
  - Makefile
  - README.md
  - RELEASING.md
  - BUILDING_CALICO.md
  - CONTRIBUTING_DOCS.md
  - CONTRIBUTING_CODE.md
  - DOC_STYLE_GUIDE.md
  - hack
  - calico_node

version: master
old_version: False

defaults:
  -
    scope:
      path: ""
    values:
      layout: docwithnav
      version: